#pragma once

#include "bsp.hpp"
#include "stm32h5xx_hal.h"
#include <cstdint>

namespace hal
{

/**
 * @brief Comprehensive driver for TI DRV8353RS / DRV8353RH Smart Gate Driver IC.
 * Supports 16-bit SPI configuration, fault reporting, and current sense amplifier (CSA) control.
 */
class Drv8353
{
public:
    // ==========================================
    // Register Address Definitions
    // ==========================================
    enum class Register : uint8_t
    {
        FAULT_STATUS_1 = 0x00,
        FAULT_STATUS_2 = 0x01,
        DRIVER_CONTROL = 0x02,
        GATE_DRIVE_HS  = 0x03,
        GATE_DRIVE_LS  = 0x04,
        OCP_CONTROL    = 0x05,
        CSA_CONTROL    = 0x06,
        DRIVER_CAL     = 0x07
    };

    // ==========================================
    // Configuration Enums
    // ==========================================

    /**
     * @brief PWM Input Modes (Register 0x02, Bits 6:5)
     * - PWM_6X: 6 independent PWM inputs (INHA, INLA, INHB, INLB, INHC, INLC). MCU controls dead time.
     * - PWM_3X: 3 PWM inputs (INHA, INHB, INHC) for high-side/low-side switching. INLx pins act as phase enables.
     *           Hardware dead time is automatically generated by DRV8353.
     * - PWM_1X: 1 PWM input (INHA) with commutation tables / Hall sensor inputs.
     * - PWM_INDEPENDENT: All 6 MOSFET gates are controlled independently without complementary logic.
     */
    enum class PwmMode : uint16_t
    {
        PWM_6X         = (0b00 << 5),
        PWM_3X         = (0b01 << 5),
        PWM_1X         = (0b10 << 5),
        PWM_INDEPENDENT= (0b11 << 5)
    };

    /**
     * @brief Peak Gate Drive Source Current (Register 0x03 & 0x04, Bits 7:4 - IDRIVEP_HS / IDRIVEP_LS)
     * Controls the slew rate (dV/dt) during MOSFET turn-ON by sourcing constant current into the gate.
     * 
     * Formula: t_rise ≈ Q_gd / IDRIVEP
     * For BSC060N10NS3G (Q_gd ≈ 7.3 nC, Q_g ≈ 44 nC):
     *   - 150 mA:  t_rise ≈ 49 ns,  t_on ≈ 290 ns (Very gentle, low EMI, higher switching loss)
     *   - 450 mA:  t_rise ≈ 16 ns,  t_on ≈ 98 ns  (Recommended sweet spot for 2 Ohm series R)
     *   - 550 mA:  t_rise ≈ 13 ns,  t_on ≈ 80 ns  (Fast switching, low loss, safe for 400ns dead time)
     *   - 1000 mA: t_rise ≈ 7.3 ns, t_on ≈ 44 ns  (Ultra-fast, check switch-node ringing with scope)
     */
    enum class IdriveP : uint16_t
    {
        IDRIVEP_50MA   = (0x0 << 4),
        IDRIVEP_100MA  = (0x2 << 4),
        IDRIVEP_150MA  = (0x3 << 4),
        IDRIVEP_300MA  = (0x4 << 4),
        IDRIVEP_350MA  = (0x5 << 4),
        IDRIVEP_400MA  = (0x6 << 4),
        IDRIVEP_450MA  = (0x7 << 4), // Balanced standard setting
        IDRIVEP_550MA  = (0x8 << 4), // Recommended for fast & efficient switching
        IDRIVEP_600MA  = (0x9 << 4),
        IDRIVEP_650MA  = (0xA << 4),
        IDRIVEP_700MA  = (0xB << 4),
        IDRIVEP_850MA  = (0xC << 4),
        IDRIVEP_900MA  = (0xD << 4),
        IDRIVEP_950MA  = (0xE << 4),
        IDRIVEP_1000MA = (0xF << 4)
    };

    /**
     * @brief Peak Gate Drive Sink Current (Register 0x03 & 0x04, Bits 3:0 - IDRIVEN_HS / IDRIVEN_LS)
     * Controls the slew rate during MOSFET turn-OFF by sinking current from the gate to ground.
     * 
     * Rule of thumb: IDRIVEN should be ~2x IDRIVEP to guarantee that the MOSFET turns OFF faster
     * than it turns ON, preventing cross-conduction (shoot-through) and overcoming Miller bounce.
     * 
     * For BSC060N10NS3G (Q_gd ≈ 7.3 nC, Q_g ≈ 44 nC):
     *   - 300 mA:  t_fall ≈ 24 ns, t_off ≈ 147 ns
     *   - 900 mA:  t_fall ≈ 8.1 ns, t_off ≈ 49 ns  (Pairs with 450mA source)
     *   - 1100 mA: t_fall ≈ 6.6 ns, t_off ≈ 40 ns  (Pairs with 550mA source)
     *   - 2000 mA: t_fall ≈ 3.7 ns, t_off ≈ 22 ns  (Maximum sink speed)
     */
    enum class IdriveN : uint16_t
    {
        IDRIVEN_100MA  = 0x0,
        IDRIVEN_200MA  = 0x2,
        IDRIVEN_300MA  = 0x3,
        IDRIVEN_600MA  = 0x4,
        IDRIVEN_700MA  = 0x5,
        IDRIVEN_800MA  = 0x6,
        IDRIVEN_900MA  = 0x7,  // Pairs with 450mA source
        IDRIVEN_1100MA = 0x8,  // Pairs with 550mA source (Recommended)
        IDRIVEN_1200MA = 0x9,
        IDRIVEN_1300MA = 0xA,
        IDRIVEN_1400MA = 0xB,
        IDRIVEN_1700MA = 0xC,
        IDRIVEN_1800MA = 0xD,
        IDRIVEN_1900MA = 0xE,
        IDRIVEN_2000MA = 0xF
    };

    /**
     * @brief Peak Gate Drive Current Duration (Register 0x04, Bits 9:8 - TDRIVE)
     * Time during which IDRIVEP / IDRIVEN peak current is actively driven onto the gate.
     * Must be longer than the total gate switching transition time (t_on / t_off).
     * If gate voltage hasn't changed within TDRIVE, Gate Drive Fault (GDF) is triggered.
     * 
     * For BSC060N10NS3G with 550mA/1100mA drive:
     *   - Total turn-on/off is < 100 ns. TDRIVE_1000NS (1 µs) gives ample margin.
     */
    enum class Tdrive : uint16_t
    {
        TDRIVE_500NS   = (0b00 << 8), // 500 ns
        TDRIVE_1000NS  = (0b01 << 8), // 1000 ns (Recommended for < 100 nC MOSFETs)
        TDRIVE_2000NS  = (0b10 << 8), // 2000 ns
        TDRIVE_4000NS  = (0b11 << 8)  // 4000 ns (For very large MOSFETs / paralleled FETs)
    };

    /**
     * @brief Hardware Dead Time (Register 0x05, Bits 9:8 - DEAD_TIME)
     * Dead time inserted between switching off one MOSFET and turning on the complementary MOSFET
     * in the same half-bridge (used in 3-PWM and 1-PWM modes).
     * 
     * With 550mA/1100mA drive (turn-off time ≈ 40 ns), a 400 ns dead time provides
     * a massive safety margin (> 10x turn-off duration) ensuring zero shoot-through risk.
     */
    enum class DeadTime : uint16_t
    {
        DT_50NS        = (0b00 << 8), // 50 ns
        DT_100NS       = (0b01 << 8), // 100 ns
        DT_200NS       = (0b10 << 8), // 200 ns
        DT_400NS       = (0b11 << 8)  // 400 ns (Requested setting)
    };

    /**
     * @brief Overcurrent Protection (OCP) Fault Response Mode (Register 0x05, Bits 7:6)
     * - LATCHED_FAULT: Shuts down all gates and asserts nFAULT pin until cleared via CLR_FLT bit or power cycle.
     * - AUTO_RETRY: Shuts down gates, waits for TRETRY (4 ms or 50 µs), then attempts to re-enable gates.
     * - REPORT_ONLY: Does not shut down gates, only pulls nFAULT pin low.
     * - DISABLED: Disables VDS and current sense overcurrent protection entirely.
     */
    enum class OcpMode : uint16_t
    {
        LATCHED_FAULT  = (0b00 << 6), // Safest for development & bench bring-up
        AUTO_RETRY     = (0b01 << 6),
        REPORT_ONLY    = (0b10 << 6),
        DISABLED       = (0b11 << 6)
    };

    /**
     * @brief OCP Deglitch Filter Time (Register 0x05, Bits 5:4)
     * Filters out brief voltage spikes during diode reverse recovery or switching transitions.
     * The overcurrent condition must persist longer than OCP_DEG before triggering a trip.
     */
    enum class OcpDeglitch : uint16_t
    {
        DEG_1US        = (0b00 << 4), // 1 µs
        DEG_2US        = (0b01 << 4), // 2 µs
        DEG_4US        = (0b10 << 4), // 4 µs (Recommended balance)
        DEG_8US        = (0b11 << 4)  // 8 µs
    };

    /**
     * @brief VDS Overcurrent Comparator Trip Threshold (Register 0x05, Bits 3:0 - VDS_LVL)
     * Measures voltage drop across the MOSFET (V_DS = I_drain * R_DS(on)).
     * If V_DS exceeds this threshold for longer than OCP_DEG, VDS overcurrent fault is tripped.
     * 
     * For BSC060N10NS3G (R_DS(on) ≈ 6 mOhm hot ≈ 10 mOhm):
     *   - VDS_0_260V -> Trips at ~26 A peak
     *   - VDS_0_600V -> Trips at ~60 A peak (Recommended default)
     *   - VDS_1_000V -> Trips at ~100 A peak
     */
    enum class VdsLevel : uint16_t
    {
        VDS_0_060V     = 0x0,
        VDS_0_130V     = 0x1,
        VDS_0_200V     = 0x2,
        VDS_0_260V     = 0x3,
        VDS_0_310V     = 0x4,
        VDS_0_450V     = 0x5,
        VDS_0_530V     = 0x6,
        VDS_0_600V     = 0x7, // 0.60 V (Recommended initial threshold)
        VDS_0_680V     = 0x8,
        VDS_0_750V     = 0x9,
        VDS_0_940V     = 0xA,
        VDS_1_130V     = 0xB,
        VDS_1_300V     = 0xC,
        VDS_1_500V     = 0xD,
        VDS_1_700V     = 0xE,
        VDS_1_880V     = 0xF
    };

    /**
     * @brief Current Sense Amplifier (CSA) Voltage Gain (Register 0x06, Bits 7:6 - CSA_GAIN)
     * Voltage gain of the 3 internal differential shunt amplifiers.
     * Output voltage: V_SOx = VREF/2 ± (I_shunt * R_shunt * CSA_GAIN)
     * 
     * For example, with R_shunt = 5 mOhm, GAIN = 20 V/V:
     *   Sensitivity = 5 mOhm * 20 = 100 mV/A (Full-scale range: ±16.5 A on 3.3V ADC).
     */
    enum class CsaGain : uint16_t
    {
        GAIN_5_VV      = (0b00 << 6), // 5 V/V
        GAIN_10_VV     = (0b01 << 6), // 10 V/V
        GAIN_20_VV     = (0b10 << 6), // 20 V/V (Requested setting)
        GAIN_40_VV     = (0b11 << 6)  // 40 V/V
    };

    /**
     * @brief Current Shunt Amplifier Overcurrent Comparator Level (Register 0x06, Bits 1:0 - SEN_LVL)
     * Trip voltage across the shunt sense resistor (V_SPx - V_SNx) for hardware overcurrent protection.
     */
    enum class SenLevel : uint16_t
    {
        SEN_0_25V      = 0b00, // 0.25 V
        SEN_0_50V      = 0b01, // 0.50 V
        SEN_0_75V      = 0b10, // 0.75 V
        SEN_1_00V      = 0b11  // 1.00 V (Maximum threshold)
    };

    // ==========================================
    // Complete Driver Configuration Struct
    // ==========================================
    struct Config
    {
        // Driver Control (0x02)
        PwmMode pwm_mode         = PwmMode::PWM_3X;
        bool otw_rep             = false; // Report overtemperature warning on nFAULT
        bool dis_gdf             = false; // Enable gate driver fault detection
        bool dis_cpuv            = false; // Enable charge pump UVLO detection

        // Gate Drive High-Side (0x03)
        IdriveP idrivep_hs       = IdriveP::IDRIVEP_550MA; // Recommended for BSC060N10NS3G & 2 Ohm series R
        IdriveN idriven_hs       = IdriveN::IDRIVEN_1100MA;// 2x source current for rapid turn-off

        // Gate Drive Low-Side (0x04)
        IdriveP idrivep_ls       = IdriveP::IDRIVEP_550MA;
        IdriveN idriven_ls       = IdriveN::IDRIVEN_1100MA;
        Tdrive tdrive            = Tdrive::TDRIVE_1000NS;  // 1 µs peak drive duration
        bool cbc                 = false;                  // Latched fault on OCP

        // OCP Control (0x05)
        DeadTime dead_time       = DeadTime::DT_400NS;     // 400 ns dead time
        OcpMode ocp_mode         = OcpMode::LATCHED_FAULT;
        OcpDeglitch ocp_deg      = OcpDeglitch::DEG_4US;
        VdsLevel vds_level       = VdsLevel::VDS_0_600V;
        bool tretry_50us         = false;                  // 4 ms retry if auto-retry mode enabled

        // Current Sense Amplifier Control (0x06)
        CsaGain csa_gain         = CsaGain::GAIN_20_VV;    // 20 V/V gain
        SenLevel sen_level       = SenLevel::SEN_1_00V;
        bool vref_div_bidir      = true;                   // VREF/2 bidirectional current sensing
        bool csa_fet_sp          = false;                  // Sense across shunt SPx (false) or SHx (true)
        bool ls_ref_gnd          = false;                  // SPx referenced to SNx (differential)
        bool dis_sen_ocp         = false;                  // Enable shunt amplifier OCP
    };

    // Fault Status Structure
    struct Faults
    {
        bool fault;
        bool vds_ocp;
        bool gdf;
        bool uvlo;
        bool otsd;
        bool vds_ha, vds_la;
        bool vds_hb, vds_lb;
        bool vds_hc, vds_lc;
        bool sa_oc, sb_oc, sc_oc;
        bool otw;
        bool cpuv;
        bool vcp_uv;
        uint16_t raw_status_1;
        uint16_t raw_status_2;
    };

    explicit Drv8353(SPI_HandleTypeDef& hspi)
        : hspi_(&hspi),
          cs_pin_(bsp::chip_select()),
          en_pin_(bsp::drv_enable()),
          fault_pin_(bsp::drv_fault())
    {
    }

    /**
     * @brief Drive ENABLE pin (PB10) HIGH to wake up and enable DRV8353.
     */
    void enable_driver()
    {
        HAL_GPIO_WritePin(en_pin_.port, en_pin_.pin, GPIO_PIN_SET);
        // t_POR: wait at least 1ms for internal voltage regulators & charge pump to stabilize
        HAL_Delay(2);
    }

    /**
     * @brief Drive ENABLE pin (PB10) LOW to put DRV8353 into low-power sleep mode.
     */
    void disable_driver()
    {
        HAL_GPIO_WritePin(en_pin_.port, en_pin_.pin, GPIO_PIN_RESET);
    }

    /**
     * @brief Check if hardware nFAULT pin is asserted (active LOW).
     */
    bool is_fault_pin_active() const
    {
        return (HAL_GPIO_ReadPin(fault_pin_.port, fault_pin_.pin) == GPIO_PIN_RESET);
    }

    /**
     * @brief Reconfigures SPI3 to 16-bit Master Mode 1 (CPOL=0, CPHA=2EDGE) and initializes DRV8353 with default config.
     */
    bool init()
    {
        return init(Config{});
    }

    /**
     * @brief Reconfigures SPI3 to 16-bit Master Mode 1 (CPOL=0, CPHA=2EDGE) and initializes DRV8353 with custom config.
     * @return true if all registers written match readback exactly.
     */
    bool init(const Config& cfg)
    {
        // 1. Configure SPI3 to 16-bit, CPOL=0, CPHA=1 (Mode 1), ~6-10 MHz max
        setup_spi();

        // 2. Chip Select idle HIGH
        cs_high();

        // 3. Drive ENABLE (PB10) HIGH to wake up DRV8353
        enable_driver();

        // 4. Clear any existing latched faults
        clear_faults();

        // 5. Construct and write register values
        uint16_t reg_02 = static_cast<uint16_t>(cfg.pwm_mode)
                        | (cfg.otw_rep  ? (1u << 8) : 0u)
                        | (cfg.dis_gdf  ? (1u << 9) : 0u)
                        | (cfg.dis_cpuv ? (1u << 10) : 0u);

        uint16_t reg_03 = (0b011 << 8) // Unlock registers
                        | static_cast<uint16_t>(cfg.idrivep_hs)
                        | static_cast<uint16_t>(cfg.idriven_hs);

        uint16_t reg_04 = (cfg.cbc ? (1u << 10) : 0u)
                        | static_cast<uint16_t>(cfg.tdrive)
                        | static_cast<uint16_t>(cfg.idrivep_ls)
                        | static_cast<uint16_t>(cfg.idriven_ls);

        uint16_t reg_05 = (cfg.tretry_50us ? (1u << 10) : 0u)
                        | static_cast<uint16_t>(cfg.dead_time)
                        | static_cast<uint16_t>(cfg.ocp_mode)
                        | static_cast<uint16_t>(cfg.ocp_deg)
                        | static_cast<uint16_t>(cfg.vds_level);

        uint16_t reg_06 = (cfg.csa_fet_sp     ? (1u << 10) : 0u)
                        | (cfg.vref_div_bidir ? (1u << 9) : 0u)
                        | (cfg.ls_ref_gnd     ? (1u << 8) : 0u)
                        | static_cast<uint16_t>(cfg.csa_gain)
                        | (cfg.dis_sen_ocp    ? (1u << 5) : 0u)
                        | static_cast<uint16_t>(cfg.sen_level);

        write_register(Register::DRIVER_CONTROL, reg_02);
        write_register(Register::GATE_DRIVE_HS,  reg_03);
        write_register(Register::GATE_DRIVE_LS,  reg_04);
        write_register(Register::OCP_CONTROL,    reg_05);
        write_register(Register::CSA_CONTROL,    reg_06);

        // 6. Read back and verify
        uint16_t rb_02 = read_register(Register::DRIVER_CONTROL);
        uint16_t rb_03 = read_register(Register::GATE_DRIVE_HS);
        uint16_t rb_04 = read_register(Register::GATE_DRIVE_LS);
        uint16_t rb_05 = read_register(Register::OCP_CONTROL);
        uint16_t rb_06 = read_register(Register::CSA_CONTROL);

        // Mask out write-only or lock bits for comparison
        bool ok = ((rb_02 & 0x07FE) == (reg_02 & 0x07FE))
               && ((rb_03 & 0x00FF) == (reg_03 & 0x00FF))
               && ((rb_04 & 0x07FF) == (reg_04 & 0x07FF))
               && ((rb_05 & 0x07FF) == (reg_05 & 0x07FF))
               && ((rb_06 & 0x07FF) == (reg_06 & 0x07FF));

        return ok;
    }

    /**
     * @brief Send CLR_FLT bit to reset latched fault flags.
     */
    void clear_faults()
    {
        uint16_t val = read_register(Register::DRIVER_CONTROL);
        write_register(Register::DRIVER_CONTROL, val | 0x01);
    }

    /**
     * @brief Enable/disable DC calibration mode on all 3 Current Sense Amplifiers.
     * When enabled, CSA inputs are shorted internally so the ADC can measure zero-current offset.
     */
    void set_csa_calibration(bool enable_cal)
    {
        uint16_t val = read_register(Register::CSA_CONTROL);
        if (enable_cal)
        {
            val |= (1u << 4) | (1u << 3) | (1u << 2); // CAL_A, CAL_B, CAL_C
        }
        else
        {
            val &= ~((1u << 4) | (1u << 3) | (1u << 2));
        }
        write_register(Register::CSA_CONTROL, val);
    }

    /**
     * @brief Read full fault status from DRV8353.
     */
    Faults read_faults()
    {
        Faults f{};
        f.raw_status_1 = read_register(Register::FAULT_STATUS_1);
        f.raw_status_2 = read_register(Register::FAULT_STATUS_2);

        f.fault   = (f.raw_status_1 & (1u << 10)) != 0;
        f.vds_ocp = (f.raw_status_1 & (1u << 9)) != 0;
        f.gdf     = (f.raw_status_1 & (1u << 8)) != 0;
        f.uvlo    = (f.raw_status_1 & (1u << 7)) != 0;
        f.otsd    = (f.raw_status_1 & (1u << 6)) != 0;
        f.vds_ha  = (f.raw_status_1 & (1u << 5)) != 0;
        f.vds_la  = (f.raw_status_1 & (1u << 4)) != 0;
        f.vds_hb  = (f.raw_status_1 & (1u << 3)) != 0;
        f.vds_lb  = (f.raw_status_1 & (1u << 2)) != 0;
        f.vds_hc  = (f.raw_status_1 & (1u << 1)) != 0;
        f.vds_lc  = (f.raw_status_1 & (1u << 0)) != 0;

        f.sa_oc   = (f.raw_status_2 & (1u << 10)) != 0;
        f.sb_oc   = (f.raw_status_2 & (1u << 9)) != 0;
        f.sc_oc   = (f.raw_status_2 & (1u << 8)) != 0;
        f.otw     = (f.raw_status_2 & (1u << 7)) != 0;
        f.cpuv    = (f.raw_status_2 & (1u << 6)) != 0;
        f.vcp_uv  = (f.raw_status_2 & (1u << 5)) != 0;

        return f;
    }

    /**
     * @brief 16-bit SPI Read from DRV8353 register.
     * Frame format: [1 (Read) | Address (4 bits) | Data (11 bits don't care)]
     */
    uint16_t read_register(Register reg)
    {
        uint16_t tx = (1u << 15) | (static_cast<uint16_t>(reg) << 11);
        uint16_t rx = transfer_16bit(tx);
        return (rx & 0x07FFu);
    }

    /**
     * @brief 16-bit SPI Write to DRV8353 register.
     * Frame format: [0 (Write) | Address (4 bits) | Data (11 bits)]
     */
    void write_register(Register reg, uint16_t data)
    {
        uint16_t tx = (0u << 15) | (static_cast<uint16_t>(reg) << 11) | (data & 0x07FFu);
        transfer_16bit(tx);
    }

private:
    SPI_HandleTypeDef* hspi_;
    pinning::GpioPin cs_pin_;
    pinning::GpioPin en_pin_;
    pinning::GpioPin fault_pin_;

    void setup_spi()
    {
        hspi_->Init.Mode               = SPI_MODE_MASTER;
        hspi_->Init.Direction          = SPI_DIRECTION_2LINES;
        hspi_->Init.DataSize           = SPI_DATASIZE_16BIT;
        hspi_->Init.CLKPolarity        = SPI_POLARITY_LOW;
        hspi_->Init.CLKPhase           = SPI_PHASE_2EDGE; // SPI Mode 1 (CPOL=0, CPHA=1)
        hspi_->Init.NSS                = SPI_NSS_SOFT;
        hspi_->Init.BaudRatePrescaler  = SPI_BAUDRATEPRESCALER_32; // ~4-8 MHz safe clock
        hspi_->Init.FirstBit           = SPI_FIRSTBIT_MSB;
        hspi_->Init.TIMode             = SPI_TIMODE_DISABLE;
        hspi_->Init.CRCCalculation     = SPI_CRCCALCULATION_DISABLE;
        hspi_->Init.NSSPMode           = SPI_NSS_PULSE_DISABLE;
        HAL_SPI_Init(hspi_);
    }

    void cs_low()
    {
        HAL_GPIO_WritePin(cs_pin_.port, cs_pin_.pin, GPIO_PIN_RESET);
    }

    void cs_high()
    {
        HAL_GPIO_WritePin(cs_pin_.port, cs_pin_.pin, GPIO_PIN_SET);
    }

    uint16_t transfer_16bit(uint16_t tx_word)
    {
        uint16_t rx_word = 0;
        cs_low();
        for (int i = 0; i < 20; ++i) { __NOP(); }

        HAL_SPI_TransmitReceive(hspi_,
                                reinterpret_cast<const uint8_t*>(&tx_word),
                                reinterpret_cast<uint8_t*>(&rx_word),
                                1,
                                50);

        for (int i = 0; i < 20; ++i) { __NOP(); }
        cs_high();
        for (int i = 0; i < 40; ++i) { __NOP(); }

        return rx_word;
    }
};

} // namespace hal
