#include "stm32g4xx_hal.h"
#include "gpio.h"

#include "platform/system_clock.hpp"

#include "heartbeat.hpp"
#include "hal/tick_hal.hpp"
#include "hal/gpio_out_hal.hpp"
#include "board.hpp"

int main()
{
  HAL_Init();
  SystemClock_Config();
  MX_GPIO_Init(); // generated by CubeMX (configure PA5 as output)

  hal::TickHal tick;

  const auto led_pin = bsp::status_led();
  hal::GpioOutHal led(led_pin.port, led_pin.pin);

  app::Heartbeat hb(500);
  hb.start(tick);

  while (true) {
    hb.update(tick, led);
  }
}
